source 'git@github.com:CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# Uncomment this line if you're using Swift
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def all_pods

pod 'Eureka'
pod 'Swinject'
pod 'RxSwift'

end

target "WargameNotesKeeper" do
  all_pods
end